version: '3'
services:
  thor-node:
    image: vechain/thor
    container_name: thor-node
    command: --network main --api-addr 0.0.0.0:8669 --disable-pruner
    volumes:
      - ./data/thor:/home/thor
    ports:
      - "8669:8669"
      - "11235:11235"
      - "11235:11235/udp"
  rpc-proxy:
    image: node:20
    container_name: rpc-proxy
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8545:8545"
    environment:
      - NODE=http://thor-node:8669
    depends_on:
      - thor-node
  graph-node:
    platform: linux/amd64
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
      - rpc-proxy
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'mainnet:http://rpc-proxy:8545'
      GRAPH_LOG: info
  ipfs:
    platform: linux/amd64
    image: ipfs/kubo:v0.17.0
    ports:
      - '5001:5001'
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements",
        "-cmax_connections=200"
      ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      # FIXME: remove this env. var. which we shouldn't need. Introduced by
      # <https://github.com/graphprotocol/graph-node/pull/3511>, maybe as a
      # workaround for https://github.com/docker/for-mac/issues/6270?
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data